name: Deploy to ECR

on: 
  push:
    branches: [ development ]

jobs:
  build:
    name: Build and Push Images
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v4

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1
      with:
        aws-region: us-east-1

    - name: Build, tag, and push images to Amazon ECR
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        WEBAPP_REPO: webapp/my_app
        DB_REPO: webapp/my_db
        IMAGE_TAG: v0.1
      run: |
        cd clo835_winter2025_assignment1

        # Build and push Web App image
        docker build -t $ECR_REGISTRY/$WEBAPP_REPO:$IMAGE_TAG -f Dockerfile .
        docker push $ECR_REGISTRY/$WEBAPP_REPO:$IMAGE_TAG

        # Build and push Database image
        docker build -t $ECR_REGISTRY/$DB_REPO:$IMAGE_TAG -f Dockerfile_mysql .
        docker push $ECR_REGISTRY/$DB_REPO:$IMAGE_TAG